from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QVBoxLayout, QHBoxLayout
from random import randint
app = QApplication([])
my_win = QWidget()
my_win.setWindowTitle('Казино')
my_win.move(900, 70)
my_win.resize(400, 200) 
my_win.show()
layoutH1 = QHBoxLayout()
layoutH2 = QHBoxLayout()
layoutH3 = QHBoxLayout()
layoutH4 = QHBoxLayout()
my_win.setWindowTitle('Казино')
but = QPushButton('Бросить кубики')
text = QLabel('Брось кубики чтобы выиграть 1000$')
text1 = QLabel('')
winner1 = QLabel('?')
winner2 = QLabel('?')
def won():
    number1 = randint(1,10)
    winner1.setText(str(number1))
    number2 = randint(1,10)
    winner2.setText(str(number2))
    if number1 == number2:
        text1.setText('Вы победили')
layoutH1.addWidget(text, alignment = Qt.AlignCenter)
layoutH2.addWidget(winner1, alignment = Qt.AlignCenter)
layoutH2.addWidget(winner2, alignment = Qt.AlignCenter)
layoutH3.addWidget(but, alignment = Qt.AlignCenter)
layoutH4.addWidget(text1, alignment = Qt.AlignCenter)
but.clicked.connect(won)
layout_main = QVBoxLayout()
layout_main.addLayout(layoutH1)
layout_main.addLayout(layoutH2)
layout_main.addLayout(layoutH3)
layout_main.addLayout(layoutH4)
my_win.setLayout(layout_main)
app.exec()